"""
utils/exporter.py
-----------------
Feature F6 (Output): export the approved RFP response to DOCX, PDF, or TXT.
Each function returns raw bytes so Streamlit's download_button can serve them.

Includes: deal/client header, every draft section with sources & flags,
the pricing table, and an audit summary.
"""

import io
from datetime import datetime

from docx import Document
from docx.shared import Pt, RGBColor
from fpdf import FPDF
from fpdf.enums import XPos, YPos

from backend.database import SessionLocal
from backend import crud


# if rfp is None:
#     raise ValueError(f"RFP {rfp_id} not found in database")
# --------------------------------------------------------------------------- #
#  Shared data assembly
# --------------------------------------------------------------------------- #
def _gather(rfp_id):
    session = SessionLocal()
    try:
        rfp = crud.get_rfp(session, rfp_id)
        sections = crud.get_draft_sections(session, rfp_id)
        pricing = crud.get_pricing(session, rfp_id)
        return rfp, sections, pricing
    finally:
        session.close()

def _sanitize(text):
    """Make text safe for fpdf core fonts (latin-1) by replacing fancy unicode."""
    if text is None:
        return ""
    replacements = {
        "—": "-", "–": "-", "“": '"', "”": '"', "‘": "'", "’": "'",
        "•": "*", "…": "...", "→": "->", "₹": "Rs.", "✓": "[x]",
        "⚑": "[flag]", "⚠": "[warn]", "◌": "[ ]", "·": "-",
    }
    for a, b in replacements.items():
        text = text.replace(a, b)
    return text.encode("latin-1", "replace").decode("latin-1")


# --------------------------------------------------------------------------- #
#  TXT
# --------------------------------------------------------------------------- #
def export_txt(rfp_id) -> bytes:
    rfp, sections, pricing = _gather(rfp_id)
    lines = []
    lines.append("=" * 60)
    lines.append(f"RFP RESPONSE — {rfp.deal_name}")
    lines.append("=" * 60)
    lines.append(f"Client:   {rfp.client_name or '-'}")
    lines.append(f"Region:   {rfp.region or '-'}")
    lines.append(f"Deadline: {rfp.deadline or '-'}")
    lines.append(f"Status:   {rfp.status}")
    lines.append(f"Reviewer: {rfp.assigned_to or '-'} ({rfp.assigned_role or '-'})")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")

    for i, s in enumerate(sections, 1):
        lines.append(f"\n{i}. {s.section_title}")
        lines.append(s.content or "")
        lines.append(s.content or "")
        if s.source and s.source != "—":
            lines.append(f"   [Source: {s.source}]")
        if s.flag_type:
            note = s.flag_note or ""
            lines.append(f"   [FLAG: {s.flag_type.upper()} — {note}]")

    if pricing:
        lines.append("\n\nPRICING TABLE")
        lines.append("-" * 50)
        for p in pricing:
            flag = "  (STALE!)" if p.stale else ""
            lines.append(f"{p.item:<32} qty {p.qty:<5} "
                         f"${p.total:>12,.2f}{flag}")
    lines.append("\n" + "=" * 60)
    lines.append("Generated by SmartRFP — human-approved before export.")
    return "\n".join(lines).encode("utf-8")


# --------------------------------------------------------------------------- #
#  DOCX
# --------------------------------------------------------------------------- #
def export_docx(rfp_id) -> bytes:
    rfp, sections, pricing = _gather(rfp_id)
    doc = Document()

    title = doc.add_heading(f"RFP Response — {rfp.deal_name}", level=0)

    meta = doc.add_paragraph()
    meta.add_run("Client: ").bold = True
    meta.add_run(f"{rfp.client_name or '-'}    ")
    meta.add_run("Region: ").bold = True
    meta.add_run(f"{rfp.region or '-'}    ")
    meta.add_run("Deadline: ").bold = True
    meta.add_run(f"{rfp.deadline or '-'}")
    sub = doc.add_paragraph()
    sub.add_run("Reviewer: ").bold = True
    sub.add_run(f"{rfp.assigned_to or '-'} ({rfp.assigned_role or '-'})    ")
    sub.add_run("Status: ").bold = True
    sub.add_run(f"{rfp.status}")

    doc.add_paragraph(f"Generated by SmartRFP on "
                      f"{datetime.now().strftime('%Y-%m-%d %H:%M')}").italic = True
    doc.add_paragraph("")

    for i, s in enumerate(sections, 1):
        doc.add_heading(f"{i}. {s.section_title}", level=1)
        doc.add_paragraph(s.content or "")
        if s.source and s.source != "—":
            p = doc.add_paragraph()
            r = p.add_run(f"Source: {s.source}")
            r.italic = True
            r.font.size = Pt(9)
            r.font.color.rgb = RGBColor(0x6b, 0x72, 0x80)
        if s.flag_type:
            p = doc.add_paragraph()
            note = getattr(s, "flag_note", "") or ""
            r = p.add_run(f"⚑ {s.flag_type.upper()}: {note}")
            r.bold = True
            r.font.color.rgb = RGBColor(0xb4, 0x53, 0x09)

    if pricing:
        doc.add_heading("Pricing Table", level=1)
        table = doc.add_table(rows=1, cols=4)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text = (
            "Item", "Qty", "Total", "Fetched / Source")
        for p in pricing:
            cells = table.add_row().cells
            cells[0].text = p.item + (" (STALE)" if p.stale else "")
            cells[1].text = str(p.qty)
            cells[2].text = f"${p.total:,.2f}"
            cells[3].text = f"{p.fetched_at} · {p.source}"

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# --------------------------------------------------------------------------- #
#  PDF
# --------------------------------------------------------------------------- #
class _PDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, "SmartRFP - RFP Response", align="R")
        self.ln(10)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f"Page {self.page_no()}", align="C")


def export_pdf(rfp_id) -> bytes:
    rfp, sections, pricing = _gather(rfp_id)
    pdf = _PDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # Helper: multi_cell that always returns the cursor to the left margin.
    def mc(h, txt):
        pdf.multi_cell(0, h, _sanitize(txt), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(20, 30, 60)
    mc(9, f"RFP Response - {rfp.deal_name}")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    mc(6, f"Client: {rfp.client_name or '-'}   |   Region: {rfp.region or '-'}   "
          f"|   Deadline: {rfp.deadline or '-'}")
    mc(6, f"Reviewer: {rfp.assigned_to or '-'} ({rfp.assigned_role or '-'})   "
          f"|   Status: {rfp.status}")
    mc(6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    pdf.ln(4)

    for i, s in enumerate(sections, 1):
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(20, 30, 60)
        mc(7, f"{i}. {s.section_title}")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        mc(6, s.content or "")
        if s.source and s.source != "—":
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(110, 110, 110)
            mc(5, f"Source: {getattr(s, 'source', '') or ''}")
        if s.flag_type:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(180, 83, 9)
            note = getattr(s, "flag_note", "") or ""

            mc(5, f"[FLAG] {s.flag_type.upper()}: {note}")
        pdf.ln(2)

    if pricing:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(20, 30, 60)
        mc(7, "Pricing Table")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(40, 40, 40)
        for p in pricing:
            flag = " (STALE)" if p.stale else ""
            mc(6, f"{p.item}{flag}  |  qty {p.qty}  |  ${p.total:,.2f}  "
                  f"|  {p.fetched_at} - {p.source}")

    out = pdf.output()  # fpdf2 returns a bytearray
    return bytes(out)
