from __future__ import annotations

import os
import sys

from dotenv import load_dotenv
from azure.core.credentials import AzureKeyCredential
from azure.search.documents.indexes import SearchIndexClient
from azure.search.documents.indexes.models import (
    HnswAlgorithmConfiguration,
    HnswParameters,
    SearchField,
    SearchFieldDataType,
    SearchIndex,
    SearchableField,
    SimpleField,
    VectorSearch,
    VectorSearchProfile,
)


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

load_dotenv()


AZURE_SEARCH_ENDPOINT = os.getenv(
    "AZURE_SEARCH_ENDPOINT",
    ""
).strip()

AZURE_SEARCH_KEY = os.getenv(
    "AZURE_SEARCH_KEY",
    ""
).strip()

AZURE_SEARCH_INDEX = os.getenv(
    "AZURE_SEARCH_INDEX",
    "smartrfp-index"
).strip()


# ---------------------------------------------------------------------------
# SmartRFP embedding configuration
# ---------------------------------------------------------------------------

EMBEDDING_DIMENSION = 1536

VECTOR_FIELD_NAME = "content_vector"
VECTOR_PROFILE_NAME = "smartrfp-vector-profile"
HNSW_ALGORITHM_NAME = "smartrfp-hnsw"


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate_configuration() -> None:
    missing = []

    if not AZURE_SEARCH_ENDPOINT:
        missing.append("AZURE_SEARCH_ENDPOINT")

    if not AZURE_SEARCH_KEY:
        missing.append("AZURE_SEARCH_KEY")

    if not AZURE_SEARCH_INDEX:
        missing.append("AZURE_SEARCH_INDEX")

    if missing:
        raise RuntimeError(
            "Missing Azure AI Search configuration: "
            + ", ".join(missing)
        )


# ---------------------------------------------------------------------------
# Create index
# ---------------------------------------------------------------------------

def create_index() -> None:
    validate_configuration()

    credential = AzureKeyCredential(
        AZURE_SEARCH_KEY
    )

    index_client = SearchIndexClient(
        endpoint=AZURE_SEARCH_ENDPOINT,
        credential=credential,
    )

    # -----------------------------------------------------------------------
    # Fields
    #
    # These fields correspond to the metadata currently generated by
    # SmartRFP's DocumentIngestion / VectorStore pipeline.
    # -----------------------------------------------------------------------

    fields = [

        # -------------------------------------------------------------------
        # Primary document key
        # Example:
        #   123_0
        #   123_1
        #   kb-15_0
        # -------------------------------------------------------------------

        SimpleField(
            name="id",
            type=SearchFieldDataType.String,
            key=True,
            filterable=True,
            sortable=True,
        ),

        # -------------------------------------------------------------------
        # RFP identifier
        #
        # Used to replace Pinecone namespaces for RFP-specific filtering.
        #
        # Example:
        #   rfp_id = "123"
        # -------------------------------------------------------------------

        SimpleField(
            name="rfp_id",
            type=SearchFieldDataType.String,
            filterable=True,
            sortable=True,
        ),

        # -------------------------------------------------------------------
        # Chunk identifier
        # -------------------------------------------------------------------

        SimpleField(
            name="chunk_id",
            type=SearchFieldDataType.Int32,
            filterable=True,
            sortable=True,
        ),

        # -------------------------------------------------------------------
        # Original filename
        # -------------------------------------------------------------------

        SearchableField(
            name="filename",
            type=SearchFieldDataType.String,
            searchable=True,
            filterable=True,
        ),

        # -------------------------------------------------------------------
        # SHA-256 hash of original document text
        # -------------------------------------------------------------------

        SimpleField(
            name="doc_hash",
            type=SearchFieldDataType.String,
            filterable=True,
        ),

        # -------------------------------------------------------------------
        # Ingestion timestamp
        #
        # Stored as string because the current SmartRFP code generates:
        #
        # datetime.now(timezone.utc).isoformat()
        #
        # Example:
        # 2026-09-17T12:34:56.123456+00:00
        # -------------------------------------------------------------------

        SimpleField(
            name="ingested_at",
            type=SearchFieldDataType.String,
            filterable=True,
            sortable=True,
        ),

        # -------------------------------------------------------------------
        # Source classification
        #
        # Examples:
        #   knowledge_base
        #   ""
        # -------------------------------------------------------------------

        SimpleField(
            name="source_type",
            type=SearchFieldDataType.String,
            filterable=True,
            facetable=True,
        ),

        # -------------------------------------------------------------------
        # Knowledge-base document ID
        #
        # Nullable because normal RFP documents don't have kb_id.
        # -------------------------------------------------------------------

        SimpleField(
            name="kb_id",
            type=SearchFieldDataType.Int32,
            filterable=True,
        ),

        # -------------------------------------------------------------------
        # Knowledge-base document type
        #
        # Examples:
        #   reference
        #   policy
        #   product
        # -------------------------------------------------------------------

        SimpleField(
            name="doc_type",
            type=SearchFieldDataType.String,
            filterable=True,
            facetable=True,
        ),

        # -------------------------------------------------------------------
        # Actual text content
        #
        # This is the text that RAG retrieves and sends to the LLM.
        # -------------------------------------------------------------------

        SearchableField(
            name="content",
            type=SearchFieldDataType.String,
            searchable=True,
        ),

        # -------------------------------------------------------------------
        # Vector embedding
        #
        # IMPORTANT:
        # EMBEDDING_DIMENSION = 1536
        #
        # This must exactly match the vectors produced by the embedding
        # service.
        # -------------------------------------------------------------------

        SearchField(
            name=VECTOR_FIELD_NAME,
            type=SearchFieldDataType.Collection(
                SearchFieldDataType.Single
            ),
            searchable=True,
            retrievable=False,
            vector_search_dimensions=EMBEDDING_DIMENSION,
            vector_search_profile_name=VECTOR_PROFILE_NAME,
        ),
    ]

    # -----------------------------------------------------------------------
    # HNSW configuration
    # -----------------------------------------------------------------------
    #
    # HNSW = Hierarchical Navigable Small World graph.
    #
    # We use cosine because your current embedding service normalizes
    # embeddings:
    #
    # normalize_embeddings=True
    #
    # -----------------------------------------------------------------------

    hnsw_algorithm = HnswAlgorithmConfiguration(
        name=HNSW_ALGORITHM_NAME,
        parameters=HnswParameters(
            m=4,
            ef_construction=400,
            ef_search=500,
            metric="cosine",
        ),
    )

    # -----------------------------------------------------------------------
    # Vector search profile
    # -----------------------------------------------------------------------

    vector_profile = VectorSearchProfile(
        name=VECTOR_PROFILE_NAME,
        algorithm_configuration_name=HNSW_ALGORITHM_NAME,
    )

    vector_search = VectorSearch(
        algorithms=[
            hnsw_algorithm,
        ],
        profiles=[
            vector_profile,
        ],
    )

    # -----------------------------------------------------------------------
    # Build index
    # -----------------------------------------------------------------------

    index = SearchIndex(
        name=AZURE_SEARCH_INDEX,
        fields=fields,
        vector_search=vector_search,
    )

    # -----------------------------------------------------------------------
    # Create or update
    # -----------------------------------------------------------------------

    print()
    print("=" * 70)
    print("SmartRFP - Azure AI Search Index")
    print("=" * 70)
    print()
    print(f"Endpoint:          {AZURE_SEARCH_ENDPOINT}")
    print(f"Index:             {AZURE_SEARCH_INDEX}")
    print(f"Vector field:      {VECTOR_FIELD_NAME}")
    print(f"Vector dimensions: {EMBEDDING_DIMENSION}")
    print(f"Vector profile:    {VECTOR_PROFILE_NAME}")
    print(f"HNSW algorithm:    {HNSW_ALGORITHM_NAME}")
    print()

    print(
        f"Creating/updating index '{AZURE_SEARCH_INDEX}'..."
    )

    result = index_client.create_or_update_index(index)

    print()
    print("=" * 70)
    print("SUCCESS")
    print("=" * 70)
    print()
    print(
        f"Azure AI Search index '{result.name}' "
        "is ready."
    )
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    try:
        create_index()

    except Exception as exc:
        print()
        print("=" * 70)
        print("ERROR")
        print("=" * 70)
        print()
        print(str(exc))
        print()

        sys.exit(1)